---
- name: "Install infrastructure"
  hosts: all

  vars_files:
    - vars/config.yml

  tasks:
    - name: "Hello world"
      ansible.builtin.debug:
        msg: "Hello world"
    - name: "Update repositories cache"
      ansible.builtin.apt:
        update_cache: true
    - name: "Install nodejs"
      ansible.builtin.apt:
        name: nodejs
    - name: "Install nginx"
      ansible.builtin.apt:
        name: nginx
    - name: "Install nginx vhost"
      ansible.builtin.template:
        src: ./templates/default.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: "0600"
