name: CI

on:
  push: ~
  workflow_dispatch: ~

jobs:
  init:
    name: "Install deps"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node to last version
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: "Install deps"
        run: npm ci

  build:
    name: "Build project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build"
        run: echo "Project built"

  tests:
    name: "Test project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test"
        run: npm run test
        continue-on-error: true

  notify:
    name: "Notify author"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Notify"
        run: |
          env
          echo "CI OK"
